# Sidekiq Jobs Schedule

# Check Character Eligibility - Every 30 minutes

# Analyze Character Communications Risk - Every 24 hours

# Analyze Character Contracts Risk - Every 24 hours

# Update Character Skill Quque - Every hour

# Update Character Skill in Training - Every hour